basePath: /v1
definitions:
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.Word:
    properties:
      point:
        type: integer
      word:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a word service api.
  title: Swagger for word api
  version: "1.0"
paths:
  /word:
    get:
      consumes:
      - application/json
      description: Get word
      parameters:
      - default: 10
        in: query
        name: limit
        required: true
        type: integer
      - default: 1
        in: query
        name: page
        required: true
        type: integer
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Word'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get word
      tags:
      - word
    post:
      consumes:
      - application/json
      description: Create a word
      parameters:
      - description: Word
        in: body
        name: word
        required: true
        schema:
          additionalProperties:
            type: integer
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a word
      tags:
      - word
swagger: "2.0"
